"""initial schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-09

Hand-written (not autogenerated) to match app/models/*.py exactly, since
this repo is developed without a live database connection available for
`alembic revision --autogenerate`. Tables are created in dependency order;
downgrade() drops them in reverse.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- users ---
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "role",
            sa.Enum("student", "instructor", "reviewer", "moderator", "admin", "super_admin", name="userrole"),
            nullable=False,
            server_default="student",
        ),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("github_url", sa.String(), nullable=True),
        sa.Column("linkedin_url", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("tutor_premium_until", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_index("ix_users_email", "users", ["email"])
    op.create_index("ix_users_username", "users", ["username"])

    # --- learning_paths ---
    op.create_table(
        "learning_paths",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("order_index", sa.Integer(), server_default="0"),
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_learning_paths_slug", "learning_paths", ["slug"])

    # --- courses ---
    op.create_table(
        "courses",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("learning_path_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("learning_paths.id"), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("is_latest_version", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("previous_version_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=True),
        sa.Column(
            "status",
            sa.Enum("draft", "published", "archived", name="coursestatus"),
            nullable=False,
            server_default="draft",
        ),
        sa.Column("order_index", sa.Integer(), server_default="0"),
        sa.Column("pass_mark_percent", sa.Integer(), nullable=False, server_default="70"),
        sa.Column("certificate_fee_kobo", sa.Integer(), nullable=True),
        sa.Column("requires_capstone", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("generated_by_ai", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("ai_source_prompt", sa.Text(), nullable=True),
    )
    op.create_index("ix_courses_slug", "courses", ["slug"])

    # --- lessons ---
    op.create_table(
        "lessons",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("video_url", sa.String(), nullable=True),
        sa.Column("estimated_minutes", sa.Integer(), nullable=True),
        sa.Column("has_quiz", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("has_playground", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("playground_starter_code", sa.Text(), nullable=True),
        sa.Column("playground_language", sa.String(), nullable=True),
        sa.Column("is_downloadable", sa.Boolean(), nullable=False, server_default=sa.true()),
    )

    # --- enrollments ---
    op.create_table(
        "enrollments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "dropped", name="enrollmentstatus"),
            nullable=False,
            server_default="active",
        ),
        sa.Column("enrolled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_eligible_for_certificate", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.UniqueConstraint("user_id", "course_id", name="uq_user_course_enrollment"),
    )

    # --- progress ---
    op.create_table(
        "progress",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("enrollment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("enrollments.id"), nullable=False),
        sa.Column("lesson_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lessons.id"), nullable=False),
        sa.Column("is_completed", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
        sa.UniqueConstraint("enrollment_id", "lesson_id", name="uq_enrollment_lesson_progress"),
    )

    # --- quizzes ---
    op.create_table(
        "quizzes",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lesson_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lessons.id"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("pass_mark_percent", sa.Integer(), nullable=False, server_default="70"),
        sa.Column("questions", postgresql.JSON(), nullable=False),
    )

    # --- quiz_attempts ---
    op.create_table(
        "quiz_attempts",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("quiz_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("quizzes.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("score_percent", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("passed", "failed", "in_progress", name="quizattemptstatus"),
            nullable=False,
            server_default="in_progress",
        ),
        sa.Column("answers", postgresql.JSON(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
    )

    # --- capstone_submissions ---
    op.create_table(
        "capstone_submissions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("repo_url", sa.String(), nullable=True),
        sa.Column("live_url", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("submitted", "under_review", "approved", "rejected", name="capstonestatus"),
            nullable=False,
            server_default="submitted",
        ),
        sa.Column("reviewer_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("reviewer_feedback", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("auto_grade_result", postgresql.JSON(), nullable=True),
    )

    # --- payments ---
    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum("certificate", "tutor_subscription", name="paymentpurpose"),
            nullable=False,
        ),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=True),
        sa.Column("amount_kobo", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False, server_default="NGN"),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "failed", "refunded", name="paymentstatus"),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("paystack_reference", sa.String(), nullable=True),
        sa.Column("paystack_channel", sa.String(), nullable=True),
        sa.Column("raw_webhook_payload", postgresql.JSON(), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("paystack_reference"),
    )
    op.create_index("ix_payments_paystack_reference", "payments", ["paystack_reference"])

    # --- certificates ---
    op.create_table(
        "certificates",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=False),
        sa.Column("enrollment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("enrollments.id"), nullable=False),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=True),
        sa.Column("certificate_number", sa.String(), nullable=False),
        sa.Column("student_name_snapshot", sa.String(), nullable=False),
        sa.Column("course_title_snapshot", sa.String(), nullable=False),
        sa.Column("grade_percent", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("valid", "revoked", name="certificatestatus"),
            nullable=False,
            server_default="valid",
        ),
        sa.Column("revoked_reason", sa.String(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pdf_url", sa.String(), nullable=True),
        sa.Column("qr_code_url", sa.String(), nullable=True),
        sa.UniqueConstraint("certificate_number"),
    )
    op.create_index("ix_certificates_certificate_number", "certificates", ["certificate_number"])

    # --- badges ---
    op.create_table(
        "badges",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(), nullable=True),
        sa.Column("trigger_key", sa.String(), nullable=True),
        sa.UniqueConstraint("name"),
    )

    # --- user_badges ---
    op.create_table(
        "user_badges",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("badge_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("badges.id"), nullable=False),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("user_id", "badge_id", name="uq_user_badge"),
    )

    # --- projects ---
    op.create_table(
        "projects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("capstone_submission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("capstone_submissions.id"), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_image_url", sa.String(), nullable=True),
        sa.Column("repo_url", sa.String(), nullable=True),
        sa.Column("live_url", sa.String(), nullable=True),
        sa.Column("is_published", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("like_count", sa.Integer(), nullable=False, server_default="0"),
    )

    # --- project_comments ---
    op.create_table(
        "project_comments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("projects.id"), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
    )

    # --- tutor_usage ---
    op.create_table(
        "tutor_usage",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("course_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("courses.id"), nullable=True),
        sa.Column("lesson_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("lessons.id"), nullable=True),
        sa.Column("prompt_char_count", sa.Integer(), nullable=True),
        sa.Column("response_char_count", sa.Integer(), nullable=True),
        sa.Column("prompt_excerpt", sa.Text(), nullable=True),
        sa.Column("model_used", sa.String(), nullable=True),
        sa.Column("low_confidence_flag", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("flagged_for_plagiarism_risk", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_premium_request", sa.Boolean(), nullable=False, server_default=sa.false()),
    )

    # --- analytics_events ---
    op.create_table(
        "analytics_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSON(), nullable=True),
    )
    op.create_index("ix_analytics_events_event_type", "analytics_events", ["event_type"])


def downgrade() -> None:
    op.drop_table("analytics_events")
    op.drop_table("tutor_usage")
    op.drop_table("project_comments")
    op.drop_table("projects")
    op.drop_table("user_badges")
    op.drop_table("badges")
    op.drop_table("certificates")
    op.drop_table("payments")
    op.drop_table("capstone_submissions")
    op.drop_table("quiz_attempts")
    op.drop_table("quizzes")
    op.drop_table("progress")
    op.drop_table("enrollments")
    op.drop_table("lessons")
    op.drop_table("courses")
    op.drop_table("learning_paths")
    op.drop_table("users")

    # Drop enum types explicitly — Postgres doesn't drop them automatically
    # when the last column using them is dropped.
    for enum_name in (
        "userrole", "coursestatus", "enrollmentstatus", "quizattemptstatus",
        "capstonestatus", "paymentpurpose", "paymentstatus", "certificatestatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
